services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    volumes:
      - ./backend:/api
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf   # Mapeando o nginx.conf da pasta docker
      - ./frontend/dist:/app/dist
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
