services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    volumes:
      - ./backend:/api
    ports:
      - "8000:8000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf   # Mapeando o nginx.conf da pasta docker
      - ./frontend/dist:/var/www/app/dist
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
